eTheatre/Models/Play.cs
using eTheatre.Data;
using eTheatre.Data.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace eTheatre.Models
{
    public class Play:IEntityBase
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string ImageURL { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public PlayCategory PlayCategory { get; set; }

        public List<Actor_play> Actors_Plays { get; set; }

        //Theatre
        public int TheatreId { get; set; }
        [ForeignKey("TheatreId")]
        public Theatre Theatre { get; set; }

        //Producer
        public int ProducerId { get; set; }
        [ForeignKey("ProducerId")]
        public Producer Producer { get; set; }
    }
}

eTheatre/Controllers/ActorsController.cs
using eTheatre.Data;
using eTheatre.Data.Services;
using eTheatre.Data.Static;
using eTheatre.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace eTheatre.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ActorsController : Controller
    {
        private readonly IActorsService _service;
        public ActorsController(IActorsService service)
        {
            _service = service;

        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }
       public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL,Bio")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.AddAsync(actor);
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);

            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);

            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,ProfilePictureURL,Bio")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.UpdateAsync(id,actor);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);

            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);

            if (actorDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);

           
            return RedirectToAction(nameof(Index));
        }
    }
}

eTheatre/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using eTheatre.Data.Cart;
using eTheatre.Data.Services;
using eTheatre.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace eTheatre.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IPlaysService _playsService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;
        public OrdersController(IPlaysService playsService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _playsService = playsService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;

        }
        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _playsService.GetPlayByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _playsService.GetPlayByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier); ;
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email); ;

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }

    }
}

eTheatre/Controllers/PlaysController.cs
using eTheatre.Data;
using eTheatre.Data.Services;
using eTheatre.Data.Static;
using eTheatre.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace eTheatre.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class PlaysController : Controller
    {
        private readonly IPlaysService _service;
        public PlaysController(IPlaysService service)
        {
            _service = service;

        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allMovies = await _service.GetAllAsync(n => n.Theatre);
            return View(allMovies);
        }


        public async Task<IActionResult> Filter(string searchString)
        {
            var allPlays = await _service.GetAllAsync(n => n.Theatre);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allPlays.Where(n => n.Name.ToLower().Contains(searchString.ToLower()) || n.Description.ToLower().Contains(searchString.ToLower())).ToList();

                //var filteredResultNew = allPlays.Where(n => string.Equals(n.Name, searchString, StringComparison.CurrentCultureIgnoreCase) || string.Equals(n.Description, searchString, StringComparison.CurrentCultureIgnoreCase)).ToList();

                return View("Index", filteredResult);
            }

            return View("Index", allPlays);
        }

        //GET: Plays/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var playDetail = await _service.GetPlayByIdAsync(id);
            return View(playDetail);
        }

        public async Task<IActionResult> Create()
        {
            var movieDropdownsData = await _service.GetNewPlayDropdownsValues();

            ViewBag.Theatres = new SelectList(movieDropdownsData.Theatres, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewPlayVM play)
        {
            if (!ModelState.IsValid)
            {
                var playDropdownsData = await _service.GetNewPlayDropdownsValues();

                ViewBag.Cinemas = new SelectList(playDropdownsData.Theatres, "Id", "Name");
                ViewBag.Producers = new SelectList(playDropdownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(playDropdownsData.Actors, "Id", "FullName");

                return View(play);
            }

            await _service.AddNewPlayAsync(play);
            return RedirectToAction(nameof(Index));
        }

        //GET: Plays/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var playDetails = await _service.GetPlayByIdAsync(id);
            if (playDetails == null) return View("NotFound");

            var response = new NewPlayVM()
            {
                Id = playDetails.Id,
                Name = playDetails.Name,
                Description = playDetails.Description,
                Price = playDetails.Price,
                StartDate = playDetails.StartDate,
                EndDate = playDetails.EndDate,
                ImageURL = playDetails.ImageURL,
                PlayCategory = playDetails.PlayCategory,
                TheatreId = playDetails.TheatreId,
                ProducerId = playDetails.ProducerId,
                ActorIds = playDetails.Actors_Plays.Select(n => n.ActorId).ToList(),
            };

            var playDropdownsData = await _service.GetNewPlayDropdownsValues();
            ViewBag.Theatres = new SelectList(playDropdownsData.Theatres, "Id", "Name");
            ViewBag.Producers = new SelectList(playDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(playDropdownsData.Actors, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewPlayVM play)
        {
            if (id != play.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var playDropdownsData = await _service.GetNewPlayDropdownsValues();

                ViewBag.Cinemas = new SelectList(playDropdownsData.Theatres, "Id", "Name");
                ViewBag.Producers = new SelectList(playDropdownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(playDropdownsData.Actors, "Id", "FullName");

                return View(play);
            }

            await _service.UpdatePlayAsync(play);
            return RedirectToAction(nameof(Index));
        }


    }
}

eTheatre/Controllers/ProducersController.cs
using eTheatre.Data;
using eTheatre.Data.Services;
using eTheatre.Data.Static;
using eTheatre.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace eTheatre.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ProducersController : Controller
    {
        
        private readonly IProducersService _service;
        public ProducersController(IProducersService service)
        {
            _service = service;

        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allProducers = await _service.GetAllAsync();
            return View(allProducers);
        }
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");
            return View(producerDetails);
        }

        //GET: producers/create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("ProfilePictureURL,FullName,Bio")] Producer producer)
        {
            if (!ModelState.IsValid) return View(producer);

            await _service.AddAsync(producer);
            return RedirectToAction(nameof(Index));
        }

        //GET: producers/edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");
            return View(producerDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProfilePictureURL,FullName,Bio")] Producer producer)
        {
            if (!ModelState.IsValid) return View(producer);

            if (id == producer.Id)
            {
                await _service.UpdateAsync(id, producer);
                return RedirectToAction(nameof(Index));
            }
            return View(producer);
        }

        //GET: producers/delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");
            return View(producerDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }


    }
}

eTheatre/Controllers/TheatresController.cs
using eTheatre.Data;
using eTheatre.Data.Services;
using eTheatre.Data.Static;
using eTheatre.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace eTheatre.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class TheatresController : Controller
    {
        private readonly ITheatresService _service;
        public TheatresController(ITheatresService service)
        {
            _service = service;

        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allTheatres = await _service.GetAllAsync();
            return View(allTheatres);
        }
       
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo,Name,Description")] Theatre theatre)
        {
            if (!ModelState.IsValid) return View(theatre);
            await _service.AddAsync(theatre);
            return RedirectToAction(nameof(Index));
        }

      
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var theatreDetails = await _service.GetByIdAsync(id);
            if (theatreDetails == null) return View("NotFound");
            return View(theatreDetails);
        }

        //Get: 
        public async Task<IActionResult> Edit(int id)
        {
            var theatreDetails = await _service.GetByIdAsync(id);
            if (theatreDetails == null) return View("NotFound");
            return View(theatreDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name,Description")] Theatre theatre)
        {
            if (!ModelState.IsValid) return View(theatre);
            await _service.UpdateAsync(id, theatre);
            return RedirectToAction(nameof(Index));
        }

        //Get: Theatres/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var theatreDetails = await _service.GetByIdAsync(id);
            if (theatreDetails == null) return View("NotFound");
            return View(theatreDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var theatreDetails = await _service.GetByIdAsync(id);
            if (theatreDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

eTheatre/Views/Plays/Create.cshtml
@model NewPlayVM
@using eTheatre.Data;
 
@{
    ViewData["Title"] = "Create a new play";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new play</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="StartDate" class="control-label"></label>
                                <input asp-for="StartDate" type="date" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="EndDate" class="control-label"></label>
                                <input asp-for="EndDate" type="date" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageURL" class="control-label"></label>
                                <input asp-for="ImageURL" class="form-control" />
                                <span asp-validation-for="ImageURL" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="TheatreId" class="control-label"></label>
                                <select asp-for="TheatreId" class="form-control" asp-items="ViewBag.Theatres"></select>
                                <span asp-validation-for="TheatreId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="PlayCategory" class="control-label"></label>
                                <select asp-for="PlayCategory" class="form-control" asp-items="Html.GetEnumSelectList<PlayCategory>()"></select>
                                <span asp-validation-for="PlayCategory" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ProducerId" class="control-label"></label>
                                <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers"></select>
                                <span asp-validation-for="ProducerId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ActorIds" class="control-label"></label>
                                <select asp-for="ActorIds" class="form-control"  asp-items="ViewBag.Actors" multiple></select>
                                <span asp-validation-for="ActorIds" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreview" />
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-danger float-right" />
                        <a class="btn btn-outline-danger" asp-action="Index">Show all</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>

@section Scripts{ 
    <script>
        $("#ImageURL").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}

eTheatre/Views/Plays/Details.cshtml
@model Play

@{
    ViewData["Title"] = "Play details";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white " style="background-color: rebeccapurple">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Name
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.ImageURL" width="100%" alt="@Model.Name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>
                        <p class="card-text">
                            <b>Theatre: </b>
                            <a asp-controller="Theatres" asp-action="Details" asp-route-id="@Model.TheatreId">
                                @Model.Theatre.Name
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Producer: </b>
                            <a asp-controller="Producers" asp-action="Details" asp-route-id="@Model.ProducerId">
                                @Model.Producer.FullName
                            </a>
                        </p>
                        <p class="card-text"><b>Category: </b>@Model.PlayCategory</p>
                        <p class="card-text"><b>Start Date: </b>@Model.StartDate.ToString("dd MMM yy")</p>
                        <p class="card-text"><b>End Date: </b>@Model.EndDate.ToString("dd MMM yy")</p>
                        <p class="card-text ">
                            <b>Status: </b>
                            @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                            {
                                <span class="badge bg-success text-white">AVAILABLE</span>
                            }
                            else if (DateTime.Now > Model.EndDate)
                            {
                                <span class="badge bg-danger text-white">EXPIRED</span>
                            }
                            else
                            {
                                <span class="badge bg-primary text-white">UPCOMING</span>
                            }
                        </p>
                        <p class="card-text">
                            <b>Actors: </b>
                            <hr />
                            <div class="row">
                                @foreach (var actor in Model.Actors_Plays)
                                {
                                    <div class="column text-center">
                                        <img class="border-info rounded-circle" src="@actor.Actor.ProfilePictureURL" style="max-width: 150px" />
                                        <br />
                                        <a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.ActorId">@actor.Actor.FullName</a>
                                    </div>
                                }
                            </div>
                        </p>

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-danger float-right" asp-action="Index">
                                Back to List
                            </a>
                            <a class="btn btn-success text-white  @((DateTime.Now > Model.EndDate) ? "disabled" : "")" style="background-color: orangered"
                               asp-controller="Orders" 
                               asp-action="AddItemToShoppingCart" asp-route-id="@Model.Id"><i class="bi bi-cart-plus"></i> Add to Cart (Price @Model.Price.ToString("c"))</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

eTheatre/Views/Plays/Index.cshtml
@model IEnumerable<Play>

@{
    ViewData["Title"] = "List of Plays";
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white " style="background-color: rebeccapurple">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name
                                   @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                   {
                                        <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                   }
                                </h5>
                            </p>
                        </div>
                    </div>
                   
                    <div class="col-md-6">
                        <div class="card-body">
                           
                            <p class="card-text"><b>Theatre: </b>@item.Theatre.Name</p>
                            <p class="card-text"><b>Category: </b>@item.PlayCategory</p>
                            <p class="card-text"><b>Start Date: </b>@item.StartDate.ToString("dd MMM yy")</p>
                            <p class="card-text"><b>End Date: </b>@item.EndDate.ToString("dd MMM yy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>

                        </div>

                    </div>
                     <div class="col-md-6">
                        <img class="rounded" src="@item.ImageURL" width="100%" alt="@item.Name">
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-danger float-right" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                                <a class="btn  text-white @((DateTime.Now > item.EndDate) ? "disabled" : "")" style="background-color: orangered" 
                                   asp-controller="Orders" 
                                   asp-action="AddItemToShoppingCart" 
                                   asp-route-id="@item.Id">
                                <i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
@await Html.PartialAsync("_CreateItem", "Plays") 